### ISSUE TITLE
Invalid Bluetooth Address

### ISSUE THREAD

**Issue by CleatonPais** [digidotcom/xbee-android#15]
I am using the code from https://www.digi.com/resources/documentation/digidocs/90001438/tasks/t_create_xb_android_app_scratch.htm

I am assuming that the format of the MAC address expected is 08:6B:D7:52:B3:7B
And the Xbee device that I have has a MAC address of 0013A20041A7A7ED 
I have tried with the following formats 0013A20041A7A7ED and 00:13:A2:00:41:A7:A7:ED
both give the same error

> Process: com.ats.digixbee, PID: 576
    java.lang.IllegalArgumentException: Invalid Bluetooth address.
        at com.digi.xbee.api.android.connection.bluetooth.AndroidBluetoothInterface.<init>(AndroidBluetoothInterface.java:124)
        at com.digi.xbee.api.android.XBee.createConnectionInterface(XBee.java:164)
        at com.digi.xbee.api.android.XBeeBLEDevice.<init>(XBeeBLEDevice.java:83)
        at com.ats.digixbee.MainActivity$2.run(MainActivity.java:49)
        at java.lang.Thread.run(Thread.java:764)

**Comment by rubenmoral** [comment]
Hi @CleatonPais,

XBee 3 modules have two MAC addresses:

- **IEEE 64-bit address** (AKA MAC address or Serial Number): is the unique identifier of the module. All XBee modules, regardless of they have Bluetooth or not, have one. The format is like 0013A2XXXXXXXXXX (separated or not by `:`). It can be obtained by reading the SH and SL parameters. In Cellular modules, this represents the IMEI.
- **Bluetooth MAC address**: is the unique identifier for the Bluetooth interface. Only XBee modules with Bluetooth have one (XBee 3). The format is like D0CF5EXXXXXX (separated or not by `:`). It can be obtained by reading the BL parameter).

In your case, you have to use the Bluetooth MAC address of the module you want to communicate with (separated by `:`), not the RF one.

Hope this helps.

**Comment by CleatonPais** [comment]
I have the Zigbee connected the android phone by USB what class should I implement to give me the best results

**Comment by rubenmoral** [comment]
It depends on how you want to communicate with the module. If over USB, then you should use the `ZigBeeDevice` class; if over Bluetooth, then use the `ZigBeeBLEDevice`. You have more information in the [library documentation](https://www.digi.com/resources/documentation/digidocs/90001438/#reference/r_instantiate_xb_device_object_android.htm).

If you need further assistance, please contact tech.support@digi.com. The GitHub issue tracker is only for bugs, not requests for help.

**Comment by CleatonPais** [comment]
Greatt Thanks for the help
