### ISSUE TITLE
Rxtx Native not working with last version of Gradle

### ISSUE THREAD

**Issue by emaleavil** [digidotcom/xbee-android#16]
I'm trying to use the library with last version of android, wrapper and android gradle plugin but I cannot import the dependency because rxtx and rxtx-native 2.2 are not found. The versions are the following:

Gradle Wrapper: 6.1.1
Android gradle plugin: 4.0.0
buildToolsVersion = 29.0.2
targetVersion = 29
compileVersion = 29

In order to work I changed my configuration to:

Gradle Wrapper: 5.5.1
Android gradle plugin: 3.5.0
buildToolsVersion = 29.0.0
targetVersion = 28
compileVersion = 28

**Comment by rubenmoral** [comment]
Hi @emaleavil,

Have you added the Digi Maven repo to the list of repositories? The rxtx library is hosted there.

```
repositories {
    ...
    maven {
        url 'http://ftp1.digi.com/support/m-repo/'
    }
}
```

**Comment by emaleavil** [comment]
Hi @rubenmoral 

Yes, I added it. And I also downloaded all jars and import using libs folder.

Thanks

**Comment by rubenmoral** [comment]
Hi @emaleavil,

Sorry for the late response. We have fixed the problem with the RxTx dependencies, there was an issue with our Maven server.

Best regards.
