### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by shanif3** [digidotcom/xbee-android#25]
Hi,
I want to build and run the exmaple "ble_configuration_sample".
Build failed bc: The specified Android SDK Build Tools version (29.0.0) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.0.
i changed it to 29.0.2 but it still make the same error
![image](https://github.com/digidotcom/xbee-android/assets/88908047/018a2eb4-67a8-498d-89ad-6f5a0c75a3ee)

Thanks in advance!

**Comment by rubenmoral** [comment]
What version of Android Studio do you have? Have you edited any gradle file (in that specific example or in the root project)?
That message usually appears as a warning, but it does not prevent to compile the project.

![image](https://github.com/digidotcom/xbee-android/assets/8180020/65257281-1d59-424d-bdb6-5f6b563174a4)

**Comment by shanif3** [comment]
Hi! i just sloved it. it was version problem :( 
thanks!
I have one more question. i opened a new [issue](https://github.com/digidotcom/xbee-android/issues/26). thanks!
